import os
import time

print ('F/')
time.sleep(0.5)
os.system('clear')
print ('F|')
time.sleep(0.5)
os.system('clear')
print ('FA/')
time.sleep(0.5)
os.system('clear')
print ('FA|')
time.sleep(0.5)
os.system('clear')
print ('FAR/')
time.sleep(0.5)
os.system('clear')
print ('FAR|')
time.sleep(0.5)
os.system('clear')
print ('FARI/')
time.sleep(0.5)
os.system('clear')
print ('FARI|')
time.sleep(0.5)
os.system('clear')
print ('FARIS/')
time.sleep(0.5)
os.system('clear')
print ('FARIS|')
time.sleep(0.5)
os.system('clear')
print ('FARIS /')
time.sleep(0.5)
os.system('clear')
print ('FARIS F|')
time.sleep(0.5)
os.system('clear')
print ('FARIS F/')
time.sleep(0.5)
os.system('clear')
print ('FARIS FA|')
time.sleep(0.5)
os.system('clear')
print ('FARIS FA/')
time.sleep(0.5)
os.system('clear')
print ('FARIS FAD|')
time.sleep(0.5)
os.system('clear')
print ('FARIS FAD/')
time.sleep(0.5)
os.system('clear')
print ('FARIS FADI|')
time.sleep(0.5)
os.system('clear')
print ('FARIS FADI/')
time.sleep(0.5)
os.system('clear')
print ('FARIS FADIL|')
time.sleep(0.5)
os.system('clear')
print ('FARIS FADIL/')
time.sleep(0.5)
os.system('clear')
print ('FARIS FADIL|')
time.sleep(0.5)
os.system('clear')
print ('FARIS FADIL/')
time.sleep(0.5)
os.system('clear')
print ('HARIS GITAMA')
time.sleep(0.5)
